// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/Article/ArticleCard.vue')['default']
    ArticleList: typeof import('./src/components/Article/ArticleList.vue')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    GAppLayout: typeof import('./src/components/GComponents/GAppLayout.vue')['default']
    GBrandedLogo: typeof import('./src/components/GComponents/GBrandedLogo.vue')['default']
    GCard: typeof import('./src/components/GComponents/GCard.vue')['default']
    GEmpty: typeof import('./src/components/GComponents/GEmpty.vue')['default']
    GImage: typeof import('./src/components/GComponents/GImage.vue')['default']
    GLogo: typeof import('./src/components/GComponents/GLogo.vue')['default']
    GPlayer: typeof import('./src/components/GComponents/GPlayer.vue')['default']
    LayoutHeader: typeof import('./src/components/Layout/LayoutHeader.vue')['default']
    LayoutMenu: typeof import('./src/components/Layout/LayoutMenu.vue')['default']
    PlaylistCard: typeof import('./src/components/Playlist/PlaylistCard.vue')['default']
    PlaylistList: typeof import('./src/components/Playlist/PlaylistList.vue')['default']
  }
}

export { }
