// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/GComponents/AppLayout.vue')['default']
    ArticleCard: typeof import('./src/components/Article/ArticleCard.vue')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GBrandedLogo: typeof import('./src/components/GComponents/GBrandedLogo.vue')['default']
    GCard: typeof import('./src/components/GComponents/GCard.vue')['default']
    GImage: typeof import('./src/components/GComponents/GImage.vue')['default']
    GLogo: typeof import('./src/components/GComponents/GLogo.vue')['default']
    GPlayer: typeof import('./src/components/GComponents/GPlayer.vue')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
